export const FEED_VIDEOS_ACTIONS = {
	FETCH_FEED_VIDEOS_START: "FEED/FETCH_FEED_VIDEOS_START",
	FETCH_FEED_VIDEOS_SUCCESS: "FEED/FETCH_FEED_VIDEOS_SUCCESS",
	FETCH_FEED_VIDEOS_FAILED: "FEED/FETCH_FEED_VIDEOS_FAILED",
};
