export const SET_CHANNEL_DETAILS = {
	FETCH_CHANNEL_DETAILS_START: "CHANNEL_DETAILS/FETCH_CHANNEL_DETAILS_START",
	FETCH_CHANNEL_DETAILS_SUCCESS:
		"CHANNEL_DETAILS/FETCH_CHANNEL_DETAILS_SUCCESS",
	FETCH_CHANNEL_DETAILS_FAILED: "CHANNEL_DETAILS/FETCH_CHANNEL_DETAILS_FAILED",
};
