export const SEARCH_FEED_ACTIONS = {
	FETCH_SEARCH_FEED_VIDEOS_START: "SEARCH_FEED/FETCH_SEARCH_FEED_VIDEOS_START",
	FETCH_SEARCH_FEED_VIDEOS_SUCCESS:
		"SEARCH_FEED/FETCH_SEARCH_FEED_VIDEOS_SUCCESS",
	FETCH_SEARCH_FEED_VIDEOS_FAILED:
		"SEARCH_FEED/FETCH_SEARCH_FEED_VIDEOS_FAILED",
};
